baseURL: http://example.org/
languageCode: ja
publishDir: docs
hasCJKLanguage: true
pygmentsCodeFences: true
pygmentsStyle: manni
pygmentsCodeFencesGuessSyntax: true
title: m-shaka's blog
theme: beautiful
author:
  name: m-shaka
  github: m-shaka
