baseURL: https://m-shaka.github.io/blog
languageCode: ja
defaultContentLanguage: ja
canonifyURLs: true
publishDir: docs
hasCJKLanguage: true
pygmentsCodeFences: true
pygmentsStyle: manni
pygmentsCodeFencesGuessSyntax: true
title: m-shaka's blog
theme: beautiful
author:
  name: m-shaka
  github: m-shaka
  twitter: schwer_metall
params:
  comments: true
  logo: 'img/avatar-icon.png'
disqusShortname: m-shaka-blog
