version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.50
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
