version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.50
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "53:fd:8f:cb:c3:b4:29:23:fc:a1:d9:44:2d:a6:9e:96"
      - checkout
      - run:
          name: "check if docs is changed"
          command: |
            if ./is_changed_dir.sh docs; then
              circleci step halt
            fi
      - run:
          name: "checkout submodule"
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: "run Hugo"
          command: HUGO_ENV=production hugo -v
      - run:
          name: "deploy"
          command: |
            git config --global user.email "buddha0818@gmail.com"
            git config --global user.name "m-shaka+circleci"
            git add docs
            git commit -m 'deploy from CircleCI'
            git push origin HEAD
